# https://kubernetes.io/docs/concepts/workloads/controllers/deployment/
apiVersion: apps/v1
kind: Deployment
metadata:
  name:  frontend-service
  namespace: default
  labels:
    app:  frontend-service
spec:
  selector:
    matchLabels:
      app: frontend-service
  replicas: 1
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      labels:
        app:  frontend-service
    spec:
      containers:
      - name:  frontend-service
        image:  suhail12/frontend:latest
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort:  80
      restartPolicy: Always
---

