# https://kubernetes.io/docs/concepts/services-networking/service/
apiVersion: v1
kind: Service
metadata:
  name: frontend-service
  namespace: default
spec:
  selector:
    app: frontend-service
  type: NodePort
  ports:
  - name: frontend-service
    protocol: TCP
    port: 80
    targetPort: 80
    nodePort: 30002
---

