# https://kubernetes.io/docs/concepts/configuration/secret/
apiVersion: v1
kind: Secret
metadata:
  name: mongodb-secret
  namespace: default
type: Opaque
stringData:
  MONGO_ROOT_USERNAME: {{ .Values.secret.root_username | b64dec | quote }}
  MONGO_ROOT_PASSWORD: {{ .Values.secret.root_password | b64dec | quote }}
  MONGO_USERNAME: {{ .Values.secret.username | b64dec | quote }}
  MONGO_PASSWORD: {{ .Values.secret.password | b64dec | quote }}
  MONGO_USERS_LIST: {{ .Values.secret.users_list | b64dec | quote }}
---

