# https://kubernetes.io/docs/concepts/services-networking/service/
apiVersion: v1
kind: Service
metadata:
  name: mongodb
  namespace: {{ .Values.namespace }}
spec:
  selector:
    app: mongodb
  type: ClusterIP
  ports:
  - name: mongodb
    protocol: TCP
    port: 27017
    targetPort: 27017
---

